@startuml
actor Kunde
boundary TicketMaske
control WebsiteController
control ParkhausController
control DatenbankController

database Datenbank
Kunde -> TicketMaske : Ticket anfragen
TicketMaske -> WebsiteController : Ticketanfrage weiterleiten
WebsiteController -> ParkhausController : Ticketanfrage weiterleiten
ParkhausController -> DatenbankController : Ticketanfrage weiterleiten
DatenbankController -> DatenbankController : Ticket generieren
DatenbankController -> Datenbank : neues Ticket einspeichern

break Datenbank nicht erreichbar
        DatenbankController --> Kunde : Fehlermeldung: Datenbank ist nicht erreichbar
end

DatenbankController --> ParkhausController : generiertes Ticket zurueckgeben
ParkhausController --> WebsiteController : generiertes Ticket zurueckgeben
@enduml